# Generated by Django 5.2.1 on 2025-08-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="is_published",
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                default="DRAFT",
                max_length=10,
            ),
        ),
    ]
